name: Prepare environment

inputs:
  java-version:
    type: string
    required: true
  java-distribution:
    type: string
    required: true

runs:
  using: composite
  steps:
  - name: Set up Java ${{ inputs.java-version }} (${{ inputs.java-distribution }})
    uses: actions/setup-java@v4
    with:
      java-version: ${{ inputs.java-version }}
      distribution: ${{ inputs.java-distribution }}
      cache: maven